silinternational/simplesamlphp-module-material

docker-compose.yml, themes/material/common-announcement.php, themes/material/common-footer.php, themes/material/common-head-elements.php, themes/material/core/loginuserpass.php, themes/material/default/error.php, themes/material/default/selectidp-links.php
Here's what comes with this PR so far:
1. When reCAPTCHA is required
2. When some error occurred while trying to Authenticate
3. How many enabled IdP's were included on the Hub
4. How many disabled IdP's were included on the Hub
5. Which IdP was chosen from the Hub
Let's discuss any further data we want to collect before finishing up this one, e.g., there's nothing on the logout or error pages right now.
=> consumers wanted more sophisticated analytics data.

themes/material/common-head-elements.php, themes/material/core/loginuserpass.php, www/styles.2.2.0.css
This will incorporate some feedback about the size of the login card on phones, resolves #9
=> Login card on phones

themes/material/common-announcement.php, themes/material/core/loginuserpass.php, themes/material/default/selectidp-links.php
When a consumer uses a library that changes PHP's error behavior, e.g, Yii turns PHP_NOTICE into Exception, optional variables can stop the app when not provided.
=> Error handling bug 

dictionaries/login.definition.json, themes/material/common-head-elements.php, themes/material/core/loginuserpass.php, themes/material/mfa/prompt-for-mfa-backupcode.php, themes/material/mfa/prompt-for-mfa-totp.php, themes/material/mfa/prompt-for-mfa-u2f.php, www/styles.2.2.3.css
this will also pick up some last minute security measures for sensitive inputs so it's going to be quickly tested in appsdev first.
=> disabled logos on hub were too small

dictionaries/mfa.definition.json
=> Fixed the Korean translation

dictionaries/mfa.definition.json, themes/material/common-head-elements.php, themes/material/mfa/new-backup-codes.php, www/styles.2.3.2.css
We had some users that were using their last code and then blowing past their new ones without grabbing a copy for themselves.  This is an attempt to deal a little better with those users.
=> Get your new backup codes

themes/material/profilereview/review.php
**Fixed:**
- The login form no longer allows double-submissions, protecting against a bug some users experienced.
=> Release 7.3.2

composer.json
This change only appears to affect what ssp-base does when it does a composer update
=> use ssp 1.17.6

dictionaries/mfa.definition.json
Upgrade to simplesamlphp 1.17.6
=> Release 7.3.4

composer.json
=> Release 7.3.5

composer.json, themes/material/core/loginuserpass.php
IE wasn't accepting the newer "onsubmit" script
=> Release 7.3.8

themes/material/core/loginuserpass.php
- Raise supported version of SimpleSAMLphp to non-vulnerable version
- Switch to official MariaDB image for databases (for local dev/testing)
=> Release 7.4.1

local.env.dist, themes/material/mfa/prompt-for-mfa-u2f.php
- Improve UX for browsers we don't support U2F in
=> Check U2F support

README.md
- Clarify/add some details in the README's debugging instructions
=> Clarify/add some details in the README's debugging instructions

development/hub1/saml20-idp-remote.php, development/hub2/saml20-idp-remote.php, themes/material/default/selectidp-links.php
- [Get logoCaption from IdP metadata to show on IdP selection page](https://github.com/silinternational/simplesamlphp-module-material/pull/115/commits/850d1449fe206f8cb55208ff025692bea715ee17)
- [add some styling and fix formatting of caption](https://github.com/silinternational/simplesamlphp-module-material/pull/115/commits/1ab34853aec555de58320e92dee76c77c05997c7)
=> Add logo caption

themes/material/default/selectidp-links.php
Fix:
- Override the `text-transform: capitalize` css property
=> capitalize is not desired

themes/material/default/selectidp-links.php
@hobbitronics 
This is based on Matt's feedback.  If it looks OK to you, feel free to merge it.  And, either way feel free to create a develop->master PR entitled `Release 8.0.1 Don't capitalize the logo captions`
=> make the target class more precise

themes/material/default/selectidp-links.php
- https://github.com/silinternational/simplesamlphp-module-material/pull/123
- https://github.com/silinternational/simplesamlphp-module-material/pull/121
=> Release 8.0.1 Don't capitalize the logo captions

themes/material/core/loginuserpass.php, themes/material/default/selectidp-links.php
- Added width related styling to the IdP discovery page header in order to allow the word wrap to styling to function
=> Release 8.0.3 Make IdP discovery page header text wrap when the window is narrow

themes/material/default/selectidp-links.php, themes/material/mfa/prompt-for-mfa-totp.php
- Text to the smartphone app (TOTP) mfa code input page that says which IdP it is for.
=> Release 8.1.0

dictionaries/mfa.definition.json, themes/material/default/selectidp-links.php, themes/material/mfa/prompt-for-mfa-totp.php
See latest image of the form on the YouTrack issue
[IDP-31](https://itse.youtrack.cloud/issue/IDP-31) In IDP 2FA prompt, remind the user which account they're getting the code for
=> Release 8.1.1 Tweak idp name reminder on TOTP form

themes/material/default/selectidp-links.php
- update some translations 
- add some missing translations
=> Release 8.1.2

dictionaries/mfa.definition.json
Remove "Smartphone" and replace with "Authenticator"
[IDP-24](https://itse.youtrack.cloud/issue/IDP-24)
=> Release - 8.1.2

themes/material/core/loginuserpass.php, themes/material/mfa/prompt-for-mfa-backupcode.php, themes/material/mfa/prompt-for-mfa-manager.php, themes/material/mfa/prompt-for-mfa-totp.php
Changed: Override input text color
[IDP-992](https://itse.youtrack.cloud/issue/IDP-992
After:
Before:
=> input color was too light IDP-992
